#!/bin/sh

rm *.j

if [ "$termprog" != "win" ]; then
  term=win
else
  term=
fi

#$term jdb -launch -classpath ../src/main/java:../target/part-II-project-1.0-SNAPSHOT.jar:../target/classes:$CLASSPATH rmk35.partIIProject.App  test.txt
java -classpath ../src/main/java:../target/part-II-project-1.0-SNAPSHOT.jar:../target/classes:$CLASSPATH rmk35.partIIProject.App  test.txt

java -jar ../jasmin.jar *.j
java -cp ../target/part-II-project-1.0-SNAPSHOT.jar:$CLASSPATH test