#!/bin/sh

rm *.j *.class

if [ "$termprog" != "win" ]; then
  term=win
else
  term=
fi

#$term jdb -launch -classpath ../src/main/java:../target/part-II-project-1.0-SNAPSHOT.jar:../target/classes:$CLASSPATH rmk35.partIIProject.Compiler  test.txt
java -classpath ../src/main/java:../target/part-II-project-1.0-SNAPSHOT.jar:../target/classes:$CLASSPATH rmk35.partIIProject.Compiler  test.txt

java -jar ../jasmin.jar -g *.j
#$term jdb -launch -classpath ../target/part-II-project-1.0-SNAPSHOT.jar:$CLASSPATH test
java -classpath ../target/part-II-project-1.0-SNAPSHOT.jar:$CLASSPATH test
