#!/bin/sh -e

JAR=../target/part-II-project-1.0-SNAPSHOT-jar-with-dependencies.jar

rm *.class || true

if [ "$termprog" != "win" ]; then
  term=win
else
  term=
fi

#$term jdb -launch -classpath ../src/main/java:$JAR:../target/classes rmk35.partIIProject.Compiler  test.txt
java -classpath ../src/main/java:$JAR:../target/classes rmk35.partIIProject.Compiler  test.txt

#$term jdb -launch -classpath .:$JAR test
java -classpath .:$JAR test
