#!/bin/sh -e

JAR=../target/part-II-project-1.0-SNAPSHOT-jar-with-dependencies.jar
CLASSPATH="-classpath .:$JAR:../target/classes:../src/main/java"
FILE=$(basename $1)

rm -f *.j *.class || true

term=win

#$term jdb -launch -classpath ../src/main/java:$JAR:../target/classes rmk35.partIIProject.Compiler ${FILE}
java -classpath ../src/main/java:$JAR:../target/classes rmk35.partIIProject.Compiler ${FILE}

#$term jdb -launch -classpath .:../src/main/java:$JAR ${FILE%.scm}
java -classpath .:$JAR ${FILE%.scm}
