#!/bin/sh -e

JAR=../../target/part-II-project-1.0-SNAPSHOT-jar-with-dependencies.jar
CLASSPATH="-classpath .:$JAR:../../target/classes:../../src/main/java"
TESTS=${1:-"imports    lambda    application    java-calls    macros    tail-calls    syntax-error    quote    exceptions    closures    macro-defining-macro    quasiquote"}

rm -f *.j *.class || true

# "win" is terminal mode for Acme
term=win

for test in $TESTS; do
  cd $test
  if [ -x ./hook ]; then ./hook; fi
  echo -n Test $test
  java $CLASSPATH rmk35.partIIProject.Compiler test.scm 2>compile-error || test -e expected-compile-failure

  test -f expected-compile-failure ||
  { timeout 1s java $CLASSPATH test > result 2>run-error || test -e expected-run-failure;
    diff result expected || { echo Error, logged in $test/run-error and output in $test/result; false; };
  }
  echo ' completed'
  cd ..
done
