(import (scheme base)
        (scheme read)
        (scheme eval)
        (scheme write)
        (scheme java))

(define foo (lambda (x) (lambda (y) x)))
(define bar (foo 1))
(define baz (foo 2))
(writeln (bar 'a))
(writeln (baz 'b))
